name: Run RSpec Tests

on:
  push:
    branches:
      - main # Run tests on pushes to the main branch
      - '**' # Optional: Run tests on all branches
  pull_request:
    branches:
      - main # Run tests on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2 # Specify your Ruby version
          bundler-cache: true # Cache gems to speed up builds

      # Step 3: Install RSpec directly
      - name: Install RSpec
        run: gem install rspec

      # Step 4: Run RSpec tests
      - name: Run RSpec
        run: bundle exec rspec